name: build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
  
    steps:
    - uses: actions/checkout@v3

    - name: scripted-build
      run: |
        pwd
        ls
        ./.github/scripts/build.sh
      shell: bash
